feat: table route for metric engine
GreptimeTeam/greptimedb pull request #3053
Opened 2023-12-29 10:56 UTC by MichaelScofield

I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

Now metric engine table can be created. Basic insertion is supported:

```text
mysql> create table physical_table(ts timestamp time index) engine = metric with (physical_metric_table = true);
Query OK, 0 rows affected (0.03 sec)

mysql> select * from information_schema.tables where engine = 'metric';
+---------------+--------------+----------------+------------+----------+--------+
| table_catalog | table_schema | table_name     | table_type | table_id | engine |
+---------------+--------------+----------------+------------+----------+--------+
| greptime      | public       | physical_table | BASE TABLE |     1044 | metric |
+---------------+--------------+----------------+------------+----------+--------+
1 row in set (0.48 sec)

mysql> create table l1(ts timestamp time index, i int) engine = metric with (on_physical_table = 'physical_table');
Query OK, 0 rows affected (0.05 sec)

mysql> insert into l1 values (1,1);
Query OK, 1 row affected (0.01 sec)

mysql> select * from l1;
+----------------------------+------+
| ts                         | i    |
+----------------------------+------+
| 1970-01-01 00:00:00.001000 |    1 |
+----------------------------+------+
1 row in set (0.03 sec)

mysql> create table l2(ts timestamp time index, s string) engine = metric with (on_physical_table = 'physical_table');
Query OK, 0 rows affected (0.05 sec)

mysql> insert into l2 values(1,"a");
Query OK, 1 row affected (0.00 sec)
```

Basic query is also supported:

```text
mysql> select * from l2;
+----------------------------+------+
| ts                         | s    |
+----------------------------+------+
| 1970-01-01 00:00:00.001000 | NULL | <-- Not expected line, might be related to some unfinished metric engine works though. Ignore it now.
| 1970-01-01 00:00:00.001000 | a    |
+----------------------------+------+
2 rows in set (0.01 sec)

```

## Checklist

- [ ]  I have written the necessary rustdoc comments.
- [ ]  I have added the necessary unit tests and integration tests.
- [ ]  This PR does not require documentation updates.

## Refer to a related PR or issue link (optional)
https://github.com/GreptimeTeam/greptimedb/issues/2864

2023-12-29 11:27 UTC, fengjiachun commented
@waynexia PTAL

2024-01-03 04:29 UTC, fengjiachun approved these changes
LGTM

2024-01-03 07:03 UTC, fengjiachun requested changes
I conducted a test: after restarting, the two logical tables l1 and l2 could not be found.

2024-01-03 13:02 UTC, MichaelScofield commented
@fengjiachun PTAL

2024-01-03 13:39 UTC, fengjiachun commented on src/datanode/src/region_server.rs
> +                    self.register_logical_regions(&engine, region_id).await?;
Create a logical table is also a `RegionChange::Register` event

2024-01-03 14:57 UTC, waynexia approved these changes
This LGTM in general :+1:

2024-01-03 14:57 UTC, waynexia commented on src/partition/src/metrics.rs
Can we remove this file and mod?

2024-01-03 14:57 UTC, waynexia commented on src/datanode/src/region_server.rs
> +    async fn register_logical_regions(
I'm wondering if it's possible to merge this logic with region open action, but it also works now. We can consider this problem later

2024-01-03 16:56 UTC, WenyXu commented on src/common/meta/src/ddl/table_meta.rs
> +                .get(LOGICAL_TABLE_METADATA_KEY)
What if the `table_options` is missing `LOGICAL_TABLE_METADATA_KEY`? Should we change to following: 
```rust 
let table_route = if task.create_table.engine == METRIC_ENGINE {
            let physical_table_name = task
                .create_table
                .table_options
                .get(LOGICAL_TABLE_METADATA_KEY)
                .context(error::UnexpectedSnafu {})?;
        
```

2024-01-04 04:03 UTC, fengjiachun approved these changes

2024-01-04 06:40 UTC, merged