feat(flow): flow node addr key
GreptimeTeam/greptimedb pull request #4164
Opened 2024-06-18 08:54 UTC by discord9

I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)
#4094
## What's changed and what's your intention?

add a key to store mapping from flownode id to addr

Please explain IN DETAIL what the changes are in this PR and why they are needed:

- Summarize your change (**mandatory**)
- How does this PR work? Need a brief introduction for the changed logic (optional)
- Describe clearly one logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

## Checklist

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.

2024-06-18 09:13 UTC, WenyXu approved these changes

2024-06-18 13:14 UTC, fengjiachun commented
I'm working on this in #4166.

2024-06-18 13:17 UTC, fengjiachun requested changes
I'm working on this in https://github.com/GreptimeTeam/greptimedb/pull/4166.

2024-06-19 03:11 UTC, closed without merging

2024-06-19 03:11 UTC, discord9 commented
Close for #4166