feat: remove InsertBatch in gRPC message
GreptimeTeam/greptimedb pull request #570
Opened 2022-11-18 07:33 UTC by Fengys123

I hereby agree to the terms of the [GreptimeDB CLA](https://gist.github.com/xtang/6378857777706e568c1949c7578592cc)

## What's changed and what's your intention?

This pr mainly remove InsertBatch in gRPC message.

## Checklist

- [x]  I have written the necessary rustdoc comments.
- [x]  I have added the necessary unit tests and integration tests.

## Refer to a related PR or issue link (optional)
#544

2022-11-21 03:01 UTC, MichaelScofield commented on src/common/grpc/src/insert.rs
> +pub struct InsertBatch {
It seems that InsertBatch is mainly used in LineWriter, can it be removed and just use columns and row count instead?

2022-11-21 03:24 UTC, MichaelScofield commented
Please also update our docs accordingly after this PR is merged.

2022-11-21 03:53 UTC, v0y4g3r requested changes

2022-11-21 03:53 UTC, v0y4g3r commented on src/common/insert/src/insert.rs
> +                _ => {}
`unreacheable!()` or return an error here to avoid expected behavior when some new variant of semantic tag is present.

2022-11-21 03:53 UTC, v0y4g3r commented on src/common/insert/src/insert.rs
> +        region_ids: vec![0], // TODO:(hl): region id should be allocated by frontend
Please also remove this todo, since setting region ids in frontend is finished.

2022-11-21 03:53 UTC, v0y4g3r commented on src/datanode/src/instance/grpc.rs
> +                    columns: insert_expr.columns.clone(),
You can simply consume `insert_expr.column` without cloning it.

2022-11-21 03:53 UTC, v0y4g3r commented on src/frontend/src/instance/influxdb.rs
> +        columns: &[Column],
rename this function to `columns_to_request`?

2022-11-21 03:53 UTC, v0y4g3r commented on src/frontend/src/expr_factory.rs
> +    async fn create_expr_by_insert_columns(
also rename this function to `create_expr_by_columns`

2022-11-21 03:57 UTC, v0y4g3r commented
Can we simply remove `InsertBatch`? We've already got `InsertRequest` for `Table` API and `InsertExpr` for gRPC API.
https://github.com/GreptimeTeam/greptimedb/blob/60c1cfee6ef32592c598d569beca28674e9df44b/src/common/grpc/src/insert.rs#L19-L27

https://github.com/GreptimeTeam/greptimedb/blob/26e037292bd442b911d108763c758e9098ba10e1/src/api/greptime/v1/database.proto#L41-L55

And `InsertExpr` seems to have all the fields in `InsertBatch`.

2022-11-21 07:03 UTC, Fengys123 commented on src/frontend/src/instance.rs
> +                    let result = self.handle_insert(insert.clone()).await;
Leave a todo here fisrt, I will refact it soon.

2022-11-21 08:37 UTC, MichaelScofield approved these changes

2022-11-24 06:04 UTC, v0y4g3r approved these changes
LGTM

2022-11-24 06:04 UTC, merged